# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c5978b761fb88086e1b91841ca9757e9f6a7112d2bc6b69713e1f4773017dd07708ce2f1ba475f729a595a4d34ea15f2345eb918153725191bf3d208e1240ab

test:
  secret_key_base: f7ede2b98350e882539bf194f01a3e70fa204e671abfdbd23083d82a682f59b98534724916102ec5b403b563b6d9b0cdbb7999968f108af2b3d488462a68f094

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
